FROM mcr.microsoft.com/dotnet/sdk:9.0

WORKDIR /app

EXPOSE 5042
EXPOSE 7038

COPY ["src/Directory.Build.props", "./"]
COPY ["src/Core.Api/Core.Api.csproj", "./Core.Api/"]
COPY ["src/Core.Application/Core.Application.csproj", "./Core.Application/"]
COPY ["src/Core.Infrastructure/Core.Infrastructure.csproj", "./Core.Infrastructure/"]
COPY ["src/Core.Domain/Core.Domain.csproj", "./Core.Domain/"]
COPY ["src/Core.Contracts/Core.Contracts.csproj", "./Core.Contracts/"]

RUN dotnet restore "./Core.Api/Core.Api.csproj"

COPY src .

CMD ["dotnet", "watch", "run", "--no-restore", "--project", "./Core.Api/Core.Api.csproj"]
