FROM mcr.microsoft.com/dotnet/sdk:9.0

WORKDIR /app

EXPOSE 80
EXPOSE 443
EXPOSE 5042
EXPOSE 7038

RUN mkdir -p /app/Core.Api/wwwroot/uploads

COPY ["src/Directory.Build.props", "./"]
COPY ["src/Core.Api/Core.Api.csproj", "./Core.Api/"]
COPY ["src/Core.Application/Core.Application.csproj", "./Core.Application/"]
COPY ["src/Core.Infrastructure/Core.Infrastructure.csproj", "./Core.Infrastructure/"]
COPY ["src/Core.Domain/Core.Domain.csproj", "./Core.Domain/"]
COPY ["src/Core.Contracts/Core.Contracts.csproj", "./Core.Contracts/"]

RUN dotnet restore "./Core.Api/Core.Api.csproj"

COPY src .

RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"

WORKDIR /

COPY ["entrypoint.sh", "./"]
RUN chmod +x ./entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]
