server:
  port: ${APP_PORT:8090}
  servlet:
    context-path: /api/v1

logging:
  level:
    ROOT: ${LOGGING_LEVEL:ERROR}

spring:
  application:
    name: Restaurant Mock Service
  webflux:
    base-path: /api/v1
  data:
    mongodb:
      host: ${MONGO_DB_HOST:localhost}
      port: ${MONGO_DB_PORT:27017}
      database: maselniczka
      username: ${MONGO_DB_USER:root}
      password: ${MONGO_DB_PASS:root}
      authentication-database: admin
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

mqtt:
  host: ${MQTT_HOST:localhost}
  port: ${MQTT_PORT:1883}
  username: ${MQTT_USER:guest}
  password: ${MQTT_PASS:guest}

management:
  endpoint:
    health:
      show-components: always
      probes:
        enabled: true
      group:
        readiness:
          include:
            - readinessState
            - rabbit
            - diskSpace
            - ping

order-update:
  update-fixed-rate: 5000
  next-update-time-min: 10
  next-update-time-max: 15

delivery:
  time-per-km: 10
  time-per-product: 1
  random-range: 5
  unit: "seconds"
