name: Core-Api
run-name: Deploy on ${{ github.ref_name }} by @${{ github.actor }}

on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master

jobs:
    dotnet-format:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: 9.0.x

            - name: Restore dependencies
              run: |
                cd src/core-api/src
                dotnet restore

            - name: Format
              run: |
                cd src/core-api/src 
                dotnet format --verify-no-changes --verbosity diagnostic
